version: '3'
services:
  web:
    container_name: VuSpace
    build: .
    volumes:
      - ./VuSpace:/var/www/html/VuSpace
      - ./log:/var/log/apache2/
    ports:
      - "80:80"
      - "443:443"
  db:
    image: mysql
    # build:
    #   context: ./
    #   dockerfile: Dockerfile-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    volumes:
      - vuspace-db:/var/lib/mysql
      - ./sql/:/sql
      - ./my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 8080:80


volumes:
  vuspace-db:
