version: "3.0"
services:
  app:
    container_name: hello-php
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
      - 8082:8082
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - my-datavolume:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  my-datavolume:
      